#!/bin/bash
cd "${BASH_SOURCE%/*}" || exit
if [[ -z ${1} ]]; then
    echo "assets-cli commands"
    exit
fi

branch()
{
    branch="master"
    attempt=$(jq -r --arg chain ${1} '.[] | select (.ac_name == $chain) | .branch' <"assetchains.json")
    if [[ ${attempt} != "null" ]] && [[ ${attempt} != "" ]]; then
        branch=${attempt}
    fi
    echo ${branch}
}

while read -r chain; do
    echo "${chain}"
    komodo/$(branch ${chain})/komodo-cli -ac_name="${chain}" "${@}"
done < <(./listassetchains.py)
