#!/bin/bash
cd ~/StakedNotary
if [[ -z $1 ]]; then
  echo "assets-cli commands"
  exit
fi

./listassetchains.py | while read coin; do
  echo $coin
  $HOME/StakedNotary/komodo/master/komodo-cli -ac_name=$coin "${@}"
done
