#!/bin/bash#!/bin/bash
cd ~/SuperNET/iguana/
bin_path="${HOME}/LabsNotary/iguana/staked/iguana"
if [[ ! -z ${1} ]]; then
    git checkout ${1}
    bin_path="${HOME}/LabsNotary/iguana/${1}/iguana"
fi

rm -f ~/LabsNotary/iguana/iguana *.o
cd secp256k1; ./m_unix; cd ..
cd ../crypto777; ./m_LP; cd ../iguana
clang -g -Wno-deprecated -c -O2 -DISNOTARYNODE=1 -DSTAKED=1 *.c ../basilisk/basilisk.c ../gecko/gecko.c ../datachain/datachain.c
clang -g  -Wno-deprecated -c -DISNOTARYNODE=1 -DSTAKED=1  main.c iguana777.c iguana_bundles.c ../basilisk/basilisk.c
clang -g -o ${bin_path} *.o ../agents/libcrypto777.a -lnanomsg -lcurl -lssl -lcrypto -lpthread -lz -lm -lsodium
