#!/bin/bash


#Change to sleepytime=false if you don't want it to loop
sleepytime=false
utxoamt=0.00010000
ntrzdamt=-0.00083600

kmdntrzaddr=RXL3YXG2ceaB6C5hfJcN4fvmLH2C34knhA

#How many transactions back to scan for notarizations
txscanamount=77777

format="%-10s %7s %6s %7s %12s\n"
ac_json=$(cat assetchains.json)
outputstats ()
{
IFS=
    count=0
    now=$(date +"%Y-%m-%d %T%z")

    printf "\n\n%-10s %7s %6s %7s %12s\n" "-ASSET-" "-NTRZd-" "-UTXO-" "-BLOX-" "-BALANCE-";

    kmdinfo=$(komodo-cli getinfo)
    printf "$format" "KMD" \
            "$(komodo-cli listtransactions "" $txscanamount | grep $kmdntrzaddr | wc -l)" \
            "$(komodo-cli listunspent | grep $utxoamt | wc -l)" \
            "$(echo $kmdinfo | awk ' /\"blocks\"/ {printf $2}' | sed 's/,//')" \
            "$(echo $kmdinfo | awk ' /\"balance\"/ {printf $2}' | sed 's/,//')"

unset IFS
for name in $(echo $ac_json | jq  -r '.[].ac_name'); do


            info=$(komodo-cli -ac_name=$name getinfo)
            #txinfo=$(komodo-cli -ac_name=$name listtransactions "" $txscanamount)
	    printf "$format" "$name" \
                    "$(komodo-cli -ac_name=$name listtransactions "" $txscanamount | grep -- $kmdntrzaddr | wc -l
)" \
                    "$(komodo-cli -ac_name=$name listunspent | grep $utxoamt | wc -l)" \
                    "$(echo $info | awk ' /\"blocks\"/ {printf $27}' | sed 's/,//')" \
"$(echo $info | awk ' /\"balance\"/ {printf $25}' | sed 's/,//')"
done

	printf "$now";
}

if [ "$sleepytime" != "false" ]
then
    while true
    do
        outputstats
        sleep $sleepytime
    done
else
    outputstats
    echo
fi
